#!/bin/bash
#
# Jonas Colmsjö, 190628

FILENAME="containers--"`hostname`"--"`date +"%Y%m%d"`

echo -e "Creating backup $FILENAME"
sudo tar -cvzpf "$FILENAME" /var/lib/lxd
s3cmd put "$FILENAME" s3://gizur-container-backups
rm "$FILENAME"
