#!/bin/bash
#
# Jonas Colmsjö, 190628


if [[ $# -ne 1 ]] ; then
    echo 'Usage: ./import-containers YYYYmmdd (create snapshots with ./snapshot-containers)'
    exit 1
fi

DATE=$1
source containers

for i in "${containers[@]}"
do
  echo -e "Importing $i using image dates $DATE (stored in /tmp) -- lxc publish $i/$DATE --alias $i-$DATE"
  s3cmd get "s3://gizur-container-backups/$i-$DATE" /tmp
  lxc image import "/tmp/$i-$DATE" --alias "$i-$DATE"
  lxc init "$i-$DATE" $i
done

lxc list
