#!/bin/bash
#
# Create a nginx container
#
# Jonas Colmsjö, 190628

declare -a cmds

cmds[0]="/usr/bin/lxc exec $1 apt-get update"
cmds[0]="/usr/bin/lxc exec $1 apt-get install -y nginx"

for i in "${cmds[@]}"
do
  echo "$i";
  eval $i;
done
