#!/bin/bash
#
# Jonas Colmsjö, 190628

if [[ $# -ne 1 ]] ; then
    echo 'Usage: ./delete-snapshots YYYYmmdd'
    exit 1
fi


DATE=$1
source containers

for i in "${containers[@]}"
do
  echo -e "Deleteing snapshot $DATE for $i"
  lxc delete $i/$DATE
done

