#!/bin/bash
#
# Jonas Colmsjö, 190628

FILENAME="chost--"`hostname`"--"`date +"%Y%m%d"`.tgz

echo -e "Creating backup $FILENAME"
sudo tar -cvzpf /tmp/"$FILENAME" /var/lib/lxd
s3cmd put /tmp/"$FILENAME" s3://gizur-container-backups
rm -f /tmp/"$FILENAME"
