#!/bin/bash
#
# Forward incoming conections
#
# Jonas Colmsjö, 190628

if [[ $# -ne 1 ]] ; then
    echo 'Usage: ./remove-forward-web CONTAINER'
    exit 1
fi

lxc config device remove $1 "port80"
lxc config device remove $1 "port443"
