#!/bin/bash
#
# Jonas Colmsjö, 190702

if [[ $# -ne 3 ]] ; then
    echo 'Usage: ./import SOURCE_DB TARGET_DB DATE'
    exit 1
fi

source setenv
DATE=$3

s3cmd get s3://gizur-application-backups/$1-$DATE.sql.gz /tmp
zcat /tmp/$1-$DATE.sql.gz | mysql --user=$MYSQL_USERNAME --password=$MYSQL_PASSWD --host=$MYSQL_HOST $2
rm /tmp/$1-$DATE.sql.gz
