#!/bin/bash
#
# Jonas Colmsjö, 190628


echo "Select Internet site, the domain name will be changed by this script"

/usr/bin/lxc exec $1 -- apt-get update
/usr/bin/lxc exec $1 --  apt-get install -y mailutils
/usr/bin/lxc file push ./etc-postfix-main.cf $1/etc/postfix/main.cf

echo -e "!!This need to be updated before running the script!!""
/usr/bin/lxc exec $1 --  echo [smtp.gmail.com]:587 USER:PASSWORD > /etc/postfix/sasl_passwd

/usr/bin/lxc exec $1 --  chmod 400 /etc/postfix/sasl_passwd
/usr/bin/lxc exec $1 --  postmap /etc/postfix/sasl_passwd
/usr/bin/lxc exec $1 --  cat /etc/ssl/certs/thawte_Primary_Root_CA.pem | tee -a /etc/postfix/cacert.pem


/usr/bin/lxc exec $1 --  systemctl restart postifx
