#!/bin/bash
#
# Create a centos php container
#
# Jonas Colmsjö, 190628


declare -a cmds
cmds[0]="/usr/bin/lxc exec $1 -- yum install -y wget nano curl git unzip which tar gcc"
cmds[1]="/usr/bin/lxc exec $1 -- yum install -y httpd php"
cmds[2]='/usr/bin/lxc exec $1 -- echo -e "<?php\nphpinfo();\n" > /var/www/html/info.php'

#
# Misc modules
# ------------

# Alternative to pecl due to problems with sasl
cmds[3]="/usr/bin/lxc exec $1 -- yum install -y cyrus-sasl-devel zlib-devel gcc-c++ php-pear php-common php-devel"
cmds[4]="/usr/bin/lxc exec $1 -- wget https://launchpad.net/libmemcached/1.0/1.0.16/+download/libmemcached-1.0.16.tar.gz"
cmds[5]="/usr/bin/lxc exec $1 -- tar -xvf libmemcached-1.0.16.tar.gz"
#RUN cd libmemcached-1.0.16; ./configure --disable-memcached-sasl
cmds[6]="/usr/bin/lxc exec $1 -- cd libmemcached-1.0.16; ./configure"
cmds[7]="/usr/bin/lxc exec $1 -- cd libmemcached-1.0.16; make; make install"
cmds[8]='/usr/bin/lxc exec $1 -- echo -e "\n" | pecl install memcached memcache'
cmds[9]='/usr/bin/lxc exec $1 -- echo "extension=memcached.so" > /etc/php.d/memcached.ini'
cmds[10]='/usr/bin/lxc exec $1 -- echo "extension=memcache.so" > /etc/php.d/memcache.ini'

# More modules
#RUN yum install -y libmemcached-devel pcre-devel cyrus-sasl-devel
#RUN yum install -y php-pecl-memcache php-pecl-memcached

cmds[11]="/usr/bin/lxc exec $1 -- yum install -y php-pecl-redis php-curl"

# Not needed: phpmyadmin mysql mysql-server httpd
cmds[12]="/usr/bin/lxc exec $1 -- yum install -y php-mysql php-gd php-imap php-ldap php-odbc php-pear php-xml \
php-xmlrpc php-mapserver php-mbstring php-mcrypt php-mssql php-snmp php-soap \
php-tidy libpng libpng-devel libjpeg \
libjpeg-devel freetype freetype-devel zlib xFree86-dev openssl openssl-devel \
krb5-devel imap-2004d"


if [[ $# -eq 0 ]] ; then
    echo 'Usage: ./php53-centos CONTAINER_NAME'
    exit 1
fi

for i in "${cmds[@]}"
do
  echo "$i";
  eval $i;
done
