#!/bin/bash
#
# Create a nginx container with PHP installed
#
# Jonas Colmsjö, 190628


declare -a cmds
cmds[0]="/usr/bin/lxc exec $1 -- apt-get update"
cmds[1]="/usr/bin/lxc exec $1 -- apt-get install -y nginx"
cmds[2]="DEBIAN_FRONTEND=noninteractive apt-get install -y wget curl procps nano apt-utils unzip"
cmds[3]="DEBIAN_FRONTEND=noninteractive apt-get install -y php-cli php-cgi php-fpm php-mysql mysql-client"

cmds[4]="DEBIAN_FRONTEND=noninteractive apt-get install -y php-soap php-mbstring php-dom"

cmds[5]="/usr/bin/lxc push ./etc-nginx-conf.d-site.conf $1/etc/nginx/conf.d/default.conf"
cmds[6]="/usr/bin/lxc push ./etc-php-7.0-fpm-pool.d-www.conf $1/etc/php/7.0/fpm/pool.d/www.conf"
cmds[7]="/usr/bin/lxc push ./usr-share-nginx-html-wp-config.php $1/usr/share/nginx/html/wp-config.php"

# Install Wordpress
cmds[8]="wget https://wordpress.org/latest.tar.gz"
cmds[9]="tar -xzf /latest.tar.gz"
cmds[10]="mv wordpress/* /usr/share/nginx/html"
cmds[11]="chown -R www-data:www-data /usr/share/nginx/html"

# Install SSL related plug-ins
cmds[12]="wget https://downloads.wordpress.org/plugin/ssl-insecure-content-fixer.2.7.0.zip"
cmds[13]="unzip ssl-insecure-content-fixer.2.7.0.zip"
cmds[14]="mv ./ssl-insecure-content-fixer /usr/share/nginx/html/wp-content/plugins/"

# Install WooCommerce
cmds[15]="wget https://downloads.wordpress.org/plugin/woocommerce.3.4.5.zip"
cmds[16]="unzip woocommerce.3.4.5.zip"
cmds[17]="mv ./woocommerce /usr/share/nginx/html/wp-content/plugins/"

cmds[18]="wget https://downloads.wordpress.org/translation/theme/storefront/2.3.3/sv_SE.zip"
cmds[19]="unzip sv_SE.zip"
cmds[20]="mkdir -p /usr/share/nginx/html/wp-content/languages/themes"
cmds[21]="mv storefront-sv_SE.*  /usr/share/nginx/html/wp-content/languages/themes/"

if [[ $# -eq 0 ]] ; then
    echo 'Usage: ./nginx CONTAINER_NAME'
    exit 1
fi

for i in "${cmds[@]}"
do
  echo "$i";
  eval $i;
done
