#!/bin/bash
#
# Create a nginx & php
#
# Jonas Colmsjö, 190701

if [[ $# -eq 0 ]] ; then
    echo 'Usage: ./php7 CONTAINER_NAME'
    exit 1
fi

# Cleanup from previous sessions (if any)
/usr/bin/lxc exec $1 -- /bin/bash -c 'rm *.gz; rm *.zip'

/usr/bin/lxc exec $1 -- apt-get update

# php-fpm php-mcrypt php-cli php-mysql php-gd php-imagick php-recode php-tidy php-xmlrpc

/usr/bin/lxc exec $1 --  apt-get install -y wget curl procps nano apt-utils unzip nginx
/usr/bin/lxc exec $1 --  apt-get install -y php-cli php-cgi php-fpm php-mysql mysql-client
/usr/bin/lxc exec $1 --  apt-get install -y php-soap php-mbstring php-dom php-gettext

/usr/bin/lxc file push ./wordpress-files/etc-nginx-conf.d-site.conf $1/etc/nginx/sites-available/default

/usr/bin/lxc exec $1 --  systemctl nginx restart
/usr/bin/lxc exec $1 --  systemctl php7.2-fpm restart

/usr/bin/lxc exec $1 -- wget https://files.phpmyadmin.net/phpMyAdmin/4.9.0.1/phpMyAdmin-4.9.0.1-all-languages.zip
/usr/bin/lxc exec $1 -- unzip phpMyAdmin-4.9.0.1-all-languages.zip
/usr/bin/lxc exec $1 -- mv /root/phpMyAdmin-4.9.0.1-all-languages/* /var/www/html
/usr/bin/lxc exec $1 -- chown -R www-data:www-data /var/www/html

# check log files in /var/log/nginx /var/log/php/php7.2-fpm.log /var/log/syslog manually
