#!/bin/bash
#
# Install whats needed for vtiger to run on CentOS 6
#
# Jonas Colmsjö, 190711

if [[ $# -ne 1 ]] ; then
    echo 'Usage: ./vtiger CONTAINER_NAME'
    exit 1
fi

# Cleanup from previous sessions (if any)
/usr/bin/lxc exec $1 -- /bin/bash -c 'rm *.gz; rm *.zip'
/usr/bin/lxc exec $1 -- yum install -y epel-release

/usr/bin/lxc exec $1 --  yum install -y wget nano curl git unzip which tar gcc
# Not sure if this is needed
/usr/bin/lxc exec $1 -- yum install -y gcc openssl-devel bzip2-devel


#
# Install Apache
# ---------------

/usr/bin/lxc exec $1 --  yum install -y httpd php

#RUN rm /var/www/html/index.html
/usr/bin/lxc exec $1 --  echo -e "<?php\nphpinfo();\n " > /var/www/html/info.php


#
# Customized ini files
# ------------------
#

# Not sure if this is needed??
#lxc file push ./vtiger-files/etc-php.ini $1/etc/php.ini
#lxc file push ./vtiger-files/etc-httpd-conf-httpd.conf $1/etc/httpd/conf/httpd.conf


#
# Install MySQL
# -------------

# Add scripts, source code for SQL-scripts and vTiger instances
#lxc file push ./vtiger-files/init-mysql.sh $1/

# Run installation
#/usr/bin/lxc exec $1 --  yum -y update; yum clean all
#/usr/bin/lxc exec $1 --  yum -y install epel-release; yum clean all
#/usr/bin/lxc exec $1 --  yum -y install mysql-server mysql pwgen bash-completion psmisc net-tools; yum clean all

# Setup admin user and load data
#/usr/bin/lxc exec $1 --  /init-mysql.sh


#
# Misc modules
# ------------

# Alternative to pecl due to problems with sasl
#/usr/bin/lxc exec $1 --  yum install -y cyrus-sasl-devel zlib-devel gcc-c++ php-pear php-common php-devel
#/usr/bin/lxc exec $1 --  wget https://launchpad.net/libmemcached/1.0/1.0.16/+download/libmemcached-1.0.16.tar.gz
#/usr/bin/lxc exec $1 --  tar -xvf libmemcached-1.0.16.tar.gz
#not used /usr/bin/lxc exec $1 --  cd libmemcached-1.0.16; ./configure --disable-memcached-sasl
#/usr/bin/lxc exec $1 --  /bin/bash -c "cd libmemcached-1.0.16; ./configure"
#/usr/bin/lxc exec $1 --  /bin/bash -c "cd libmemcached-1.0.16; make; make install"
#/usr/bin/lxc exec $1 --  /bin/bash -c 'echo -e "\n" | pecl install memcached memcache'
#/usr/bin/lxc exec $1 --  /bin/bash -c 'echo "extension=memcached.so" > /etc/php.d/memcached.ini'
#/usr/bin/lxc exec $1 --  /bin/bash -c 'echo "extension=memcache.so" > /etc/php.d/memcache.ini'

# More modules
/usr/bin/lxc exec $1 --  yum install -y libmemcached-devel pcre-devel cyrus-sasl-devel
/usr/bin/lxc exec $1 --  yum install -y php-pecl-memcache php-pecl-memcached

#yum install -y libmemcached php-pecl-memcache


/usr/bin/lxc exec $1 --  yum install -y php-pecl-redis php-curl

# Not needed: phpmyadmin mysql mysql-server httpd
/usr/bin/lxc exec $1 --  yum install -y php-mysql php-gd php-imap php-ldap php-odbc php-pear php-xml \
php-xmlrpc php-mapserver php-mbstring php-mcrypt php-mssql php-snmp php-soap \
php-tidy libpng libpng-devel libjpeg \
libjpeg-devel freetype freetype-devel zlib xFree86-dev openssl openssl-devel \
krb5-devel imap-2004d

#/usr/bin/lxc exec $1 --  /bin/bash -c 'cd `pear config-get php_dir`; mv .channels .channels-broken; pear update-channels'
#/usr/bin/lxc exec $1 --  /bin/bash -c 'echo -e "\n" | pecl upgrade'
#/usr/bin/lxc exec $1 --  /bin/bash -c 'echo -e "\n" | pecl install apc'


# Add batches here since it changes often (use cache when building)
#lxc file push ./vtiger-files/batches.py $1/
/usr/bin/lxc exec $1 --  ./batches.sh /

# Run backup job every hour
lxc file push ./vtiger-files/backup.sh $1/
/usr/bin/lxc exec $1 --  echo '0 1 * * *  /bin/bash -c "/backup.sh"' > /mycron

/usr/bin/lxc exec $1 --  crontab /mycron


/usr/bin/lxc exec $1 --  mkdir /apps

/usr/bin/lxc exec $1 -- service httpd start
/usr/bin/lxc exec $1 -- chkconfig httpd on


# 
# Add to /etc/sysconfig/httpd:
#
#exort db_server=
#export db_port=
#export db_username=
#export db_password=
#export db_name=
#export absolute_uri=
#export s3_access_key=
#export s3_secret_key=
#export aws_key=
#export aws_secret=
#export mailserver=
#export memcached_server=
#export redis_server=

#
# Add this this to /etc/httpd/conf/httpd.conf
# PassEnv db_server db_port db_username db_password db_name absolute_uri s3_access_key s3_secret_key aws_key mailserver memcached_server redis_server
#
